name: Deploy to Firebase Hosting on Merge
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        working-directory: ./front
        env:
          CI: false
          REACT_APP_API_BASE_URL: ${{ secrets.API_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PFE_KOLLECTION }}
          projectId: pfe-kollection
          entryPoint: ./front
          channelId: live
