name: API CI dev

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    strategy:
      matrix:
        node-version: [20.9.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          working-directory: ./api


      - name: Run CI command
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: vercel --token=${{ secrets.VERCEL_TOKEN }}
